/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as ProtocolsRouteImport } from './routes/protocols'
import { Route as IncidentsIndexRouteImport } from './routes/incidents.index'
import { Route as IncidentsIncidentIdRouteImport } from './routes/incidents.$incidentId'
import { Route as ProtocolsIndexRouteImport } from './routes/protocols.index'
import { Route as ProtocolsProtocolIdRouteImport } from './routes/protocols.$protocolId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocolsRoute = ProtocolsRouteImport.update({
  id: '/protocols',
  path: '/protocols',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsIndexRoute = IncidentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IncidentsRoute,
} as any)
const IncidentsIncidentIdRoute = IncidentsIncidentIdRouteImport.update({
  id: '/$incidentId',
  path: '/$incidentId',
  getParentRoute: () => IncidentsRoute,
} as any)
const ProtocolsIndexRoute = ProtocolsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtocolsRoute,
} as any)
const ProtocolsProtocolIdRoute = ProtocolsProtocolIdRouteImport.update({
  id: '/$protocolId',
  path: '/$protocolId',
  getParentRoute: () => ProtocolsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/incidents': typeof IncidentsRouteWithChildren
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/protocols': typeof ProtocolsRouteWithChildren
  '/incidents/$incidentId': typeof IncidentsIncidentIdRoute
  '/protocols/$protocolId': typeof ProtocolsProtocolIdRoute
  '/incidents/': typeof IncidentsIndexRoute
  '/protocols/': typeof ProtocolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/incidents/$incidentId': typeof IncidentsIncidentIdRoute
  '/protocols/$protocolId': typeof ProtocolsProtocolIdRoute
  '/incidents': typeof IncidentsIndexRoute
  '/protocols': typeof ProtocolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/incidents': typeof IncidentsRouteWithChildren
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/protocols': typeof ProtocolsRouteWithChildren
  '/incidents/$incidentId': typeof IncidentsIncidentIdRoute
  '/protocols/$protocolId': typeof ProtocolsProtocolIdRoute
  '/incidents/': typeof IncidentsIndexRoute
  '/protocols/': typeof ProtocolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/incidents'
    | '/login'
    | '/overview'
    | '/protocols'
    | '/incidents/$incidentId'
    | '/protocols/$protocolId'
    | '/incidents/'
    | '/protocols/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/login'
    | '/overview'
    | '/incidents/$incidentId'
    | '/protocols/$protocolId'
    | '/incidents'
    | '/protocols'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/incidents'
    | '/login'
    | '/overview'
    | '/protocols'
    | '/incidents/$incidentId'
    | '/protocols/$protocolId'
    | '/incidents/'
    | '/protocols/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  IncidentsRoute: typeof IncidentsRouteWithChildren
  LoginRoute: typeof LoginRoute
  OverviewRoute: typeof OverviewRoute
  ProtocolsRoute: typeof ProtocolsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocols': {
      id: '/protocols'
      path: '/protocols'
      fullPath: '/protocols'
      preLoaderRoute: typeof ProtocolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents/': {
      id: '/incidents/'
      path: '/'
      fullPath: '/incidents/'
      preLoaderRoute: typeof IncidentsIndexRouteImport
      parentRoute: typeof IncidentsRoute
    }
    '/incidents/$incidentId': {
      id: '/incidents/$incidentId'
      path: '/$incidentId'
      fullPath: '/incidents/$incidentId'
      preLoaderRoute: typeof IncidentsIncidentIdRouteImport
      parentRoute: typeof IncidentsRoute
    }
    '/protocols/': {
      id: '/protocols/'
      path: '/'
      fullPath: '/protocols/'
      preLoaderRoute: typeof ProtocolsIndexRouteImport
      parentRoute: typeof ProtocolsRoute
    }
    '/protocols/$protocolId': {
      id: '/protocols/$protocolId'
      path: '/$protocolId'
      fullPath: '/protocols/$protocolId'
      preLoaderRoute: typeof ProtocolsProtocolIdRouteImport
      parentRoute: typeof ProtocolsRoute
    }
  }
}

interface IncidentsRouteChildren {
  IncidentsIncidentIdRoute: typeof IncidentsIncidentIdRoute
  IncidentsIndexRoute: typeof IncidentsIndexRoute
}

const IncidentsRouteChildren: IncidentsRouteChildren = {
  IncidentsIncidentIdRoute: IncidentsIncidentIdRoute,
  IncidentsIndexRoute: IncidentsIndexRoute,
}

const IncidentsRouteWithChildren = IncidentsRoute._addFileChildren(
  IncidentsRouteChildren,
)

interface ProtocolsRouteChildren {
  ProtocolsProtocolIdRoute: typeof ProtocolsProtocolIdRoute
  ProtocolsIndexRoute: typeof ProtocolsIndexRoute
}

const ProtocolsRouteChildren: ProtocolsRouteChildren = {
  ProtocolsProtocolIdRoute: ProtocolsProtocolIdRoute,
  ProtocolsIndexRoute: ProtocolsIndexRoute,
}

const ProtocolsRouteWithChildren = ProtocolsRoute._addFileChildren(
  ProtocolsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  IncidentsRoute: IncidentsRouteWithChildren,
  LoginRoute: LoginRoute,
  OverviewRoute: OverviewRoute,
  ProtocolsRoute: ProtocolsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
